name: Build Debug and Check Quality

on:
  workflow_dispatch:

jobs:
  build-debug-and-check-quality:
    name: Build debug and check quality
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 15
    steps:

      - name: Check the repository
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Assemble debug
        run: ./gradlew assembleDebug
