name: Build Debug and Check Quality

on:
  workflow_dispatch:

jobs:
  build-debug-and-check-quality:
    name: Build debug and check quality
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - name: Check the repository
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: gradle

      - name: Assemble debug
        run: ./gradlew assembleDebug
