name: Sample

on:
  workflow_dispatch:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "This is a one-line script!"

      - name: Run a multi-line script
        run: |
          echo "This is a multi-line script! (1/3)"
          echo "This is a multi-line script! (2/3)"
          echo "This is a multi-line script! (3/3)"
